# Generated by Django 5.1 on 2025-07-23 04:43

import app.core.models.base
import django.contrib.postgres.functions
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True),
                ),
                (
                    "modified_at",
                    models.DateTimeField(
                        auto_now=True, null=True
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Label for Wallet",
                        max_length=255,
                    ),
                ),
                (
                    "balance",
                    app.core.models.base.DecimalCustom(
                        decimal_places=18,
                        default=0,
                        help_text="Up to date balance amount with 18 precision points",
                        max_digits=36,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("balance__gte", 0)
                        ),
                        name="balance_non_negative",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PointOfSale",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True),
                ),
                (
                    "modified_at",
                    models.DateTimeField(
                        auto_now=True, null=True
                    ),
                ),
                (
                    "txid",
                    models.UUIDField(
                        db_default=django.contrib.postgres.functions.RandomUUID(),
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "amount",
                    app.core.models.base.DecimalCustom(
                        decimal_places=18,
                        help_text="Transction amount could be negative and positive, should not exceed Wallet's total balance amount",
                        max_digits=36,
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        help_text="Foreign key to wallet",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="core.wallet",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
