# Generated by Django 5.1 on 2025-07-22 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "core",
            "0002_create_sequence",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="pointofsale",
            name="wallet_id",
            field=models.ForeignKey(
                help_text="Foreign key to wallet",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transactions",
                to="core.wallet",
            ),
        ),
    ]
